---
   - name: copy create domain python script
     template: src=domain_with_node.py dest=/tmp/weblogic owner="{{ oracle_user }}" group="{{ oracle_group }}"
   - name: copy create domain python script
     template: src=domain.properties dest=/tmp/weblogic owner="{{ oracle_user }}" group="{{ oracle_group }}"
   - name: copy create domain python script
     template: src=domain_creation.sh dest=/tmp/weblogic owner="{{ oracle_user }}" group="{{ oracle_group }}"
   - name: Execute create domain script
     #become: yes
     command: sh /tmp/weblogic/domain_creation.sh
   - name: permission
     become: yes
     file: dest="{{ middleware_home }}" owner="{{ oracle_user }}" group="{{ oracle_group }}" mode=0775 recurse=yes
