---
   - name: Copy Nodemanager Properties file
     template: src=nodemanager.properties dest="{{ nodemanager_home }}" owner="{{ oracle_user }}" group="{{ oracle_group }}"
     tags:
     - start-nodemanager

   - name: Copy nodemanager systemd script
     become: yes
     template: src=nodemanager.service dest=/etc/systemd/system/  mode=0664
     tags:
     - start-nodemanager
   - name: Enable nodemanager as linux service
     become: yes
     command: 'systemctl enable nodemanager'
     tags:
     - start-nodemanager
   - name: Start Node Manager
     become: yes
     command: 'systemctl start nodemanager'
     tags:
     - start-nodemanager
   - name: Start Node Manager
     become: yes
     command: 'systemctl stop nodemanager'
     tags:
     - start-nodemanager
